name: agentic_reasoning
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope
  - asttokens
  - bzip2
  - ca-certificates
  - comm
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - importlib-metadata
  - ipykernel
  - jedi
  - jupyter_client
  - jupyter_core
  - krb5
  - libcxx
  - libedit
  - libffi
  - libsodium
  - matplotlib-inline
  - ncurses
  - nest-asyncio
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pip
  - platformdirs
  - prompt-toolkit
  - ptyprocess
  - pure_eval
  - pygments
  - python=3.11
  - python-dateutil
  - pyzmq
  - readline
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
  - pip:
      - agno
      - aiofiles
      - aiohappyeyeballs
      - aiohttp
      - aiohttp-cors
      - aiosignal
      - airportsdata
      - alembic
      - annotated-types
      - anyio
      - anytree
      - apscheduler
      - asgiref
      - astor
      - asyncer
      - attrs
      - autograd
      - babel
      - backcall
      - backoff
      - bcrypt
      - beartype
      - beautifulsoup4
      - blake3
      - bleach
      - build
      - cachetools
      - certifi
      - cffi
      - chardet
      - charset-normalizer
      - chroma-hnswlib
      - chromadb
      - click
      - cloudpickle
      - coloredlogs
      - colorful
      - colorlog
      - compressed-tensors
      - contourpy
      - courlan
      - cryptography
      - cycler
      - dataclasses-json
      - datasets
      - dateparser
      - defusedxml
      - deprecated
      - depyf
      - dill
      - diskcache
      - distlib
      - distro
      - dnspython
      - docopt
      - docstring-parser
      - dspy
      - dspy-ai
      - duckduckgo-search
      - durationpy
      - einops
      - email-validator
      - emoji
      - eval-type-backport
      - fastapi
      - fastapi-cli
      - fastapi-sso
      - fastjsonschema
      - ffmpy
      - filelock
      - filetype
      - flatbuffers
      - fonttools
      - frozenlist
      - fsspec
      - future
      - gensim
      - gguf
      - git-filter-repo
      - gitdb
      - gitpython
      - google-api-core
      - google-auth
      - googleapis-common-protos
      - gradio
      - gradio-client
      - graspologic
      - graspologic-native
      - grpcio
      - grpcio-tools
      - gunicorn
      - h11
      - h2
      - hnswlib
      - hpack
      - html5lib
      - htmldate
      - httpcore
      - httptools
      - httpx
      - httpx-sse
      - huggingface-hub
      - humanfriendly
      - hyperframe
      - hyppo
      - idna
      - importlib-resources
      - interegular
      - ipython
      - jinja2
      - jiter
      - joblib
      - json-repair
      - jsonpatch
      - jsonpath-python
      - jsonpointer
      - jsonschema
      - jsonschema-specifications
      - jupyterlab-pygments
      - justext
      - kiwisolver
      - kubernetes
      - langchain
      - langchain-community
      - langchain-core
      - langchain-huggingface
      - langchain-openai
      - langchain-qdrant
      - langchain-text-splitters
      - langdetect
      - langsmith
      - lark
      - litellm
      - llvmlite
      - lm-format-enforcer
      - lxml
      - lxml-html-clean
      - magicattr
      - mako
      - markdown-it-py
      - markupsafe
      - marshmallow
      - matplotlib
      - mdurl
      - mistral-common
      - mistune
      - mmh3
      - monotonic
      - mpmath
      - msgpack
      - msgspec
      - multidict
      - multiprocess
      - mypy-extensions
      - nano-graphrag
      - nano-vectordb
      - nbclient
      - nbconvert
      - nbformat
      - neo4j
      - networkx
      - nltk
      - numba
      - numpy
      - nvidia-ml-py
      - oauthlib
      - olefile
      - onnxruntime
      - openai
      - opencensus
      - opencensus-context
      - opencv-python-headless
      - opentelemetry-api
      - opentelemetry-exporter-otlp-proto-common
      - opentelemetry-exporter-otlp-proto-grpc
      - opentelemetry-instrumentation
      - opentelemetry-instrumentation-asgi
      - opentelemetry-instrumentation-fastapi
      - opentelemetry-proto
      - opentelemetry-sdk
      - opentelemetry-semantic-conventions
      - opentelemetry-util-http
      - optuna
      - orjson
      - outlines
      - outlines-core
      - overrides
      - pandas
      - pandocfilters
      - partial-json-parser
      - patsy
      - pdfminer-six
      - pdfplumber
      - phidata
      - pillow
      - pipreqs
      - portalocker
      - posthog
      - pot
      - primp
      - prometheus-client
      - prometheus-fastapi-instrumentator
      - propcache
      - proto-plus
      - protobuf
      - psutil
      - py-cpuinfo
      - py-spy
      - pyarrow
      - pyarrow-hotfix
      - pyasn1
      - pyasn1-modules
      - pycountry
      - pycparser
      - pydantic
      - pydantic-core
      - pydantic-settings
      - pydub
      - pyjwt
      - pynacl
      - pynndescent
      - pyparsing
      - pypdf
      - pypdfium2
      - pypika
      - pyproject-hooks
      - python-dotenv
      - python-iso639
      - python-magic
      - python-multipart
      - python-oxmsg
      - pytz
      - pyyaml
      - qdrant-client
      - rapidfuzz
      - ray
      - redis
      - referencing
      - regex
      - requests
      - requests-oauthlib
      - requests-toolbelt
      - rich
      - rich-toolkit
      - rpds-py
      - rq
      - rsa
      - ruff
      - safehttpx
      - safetensors
      - scikit-learn
      - scipy
      - seaborn
      - semantic-version
      - sentence-transformers
      - sentencepiece
      - shellingham
      - smart-open
      - smmap
      - sniffio
      - soupsieve
      - sqlalchemy
      - starlette
      - statsmodels
      - structlog
      - sympy
      - tenacity
      - threadpoolctl
      - tiktoken
      - tinycss2
      - tld
      - tokenizers
      - toml
      - tomli
      - tomlkit
      - torch
      - torchvision
      - tqdm
      - trafilatura
      - transformers
      - typer
      - typing-inspect
      - tzdata
      - tzlocal
      - ujson
      - umap-learn
      - unstructured
      - unstructured-client
      - urllib3
      - uvicorn
      - uvloop
      - virtualenv
      - vllm
      - watchfiles
      - webencodings
      - websocket-client
      - websockets
      - wikipedia
      - wrapt
      - xxhash
      - yarg
      - yarl